"""relationships

Revision ID: 7a1c9c0f7bb1
Revises: ad51aa5126ac
Create Date: 2023-10-07 22:46:44.330058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1c9c0f7bb1'
down_revision = 'ad51aa5126ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'customer_id')
    # ### end Alembic commands ###
